# Generated by Django 5.2.1 on 2025-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
